### PR TITLE
Decision Tree `prune` method

### PR DESCRIPTION
**Pull request by varunagrawal**
Added a new method to prune decision trees in general based on a predicate function.
We can now run this method on the `DecisionTreeFactor` and use the pruned tree to update the conditionals.

### CODE REVIEW

**Comment by varunagrawal** [comment]
@dellaert this PR affects `DecisionTree` by adding a method and modifying some others, so your review will be much appreciated. :slightly_smiling_face:

**Review by dellaert — CHANGES_REQUESTED** [review]
Not functional, and don't see a reason why it would not be.

**Comment by dellaert** [comment]
Btw, since this is a pure GTSAM PR, After you make it functional, you might want to make a PR on GTSAM develop rather than the fork?

**Comment by varunagrawal** [comment]
I thought this method was fully-functional. For each leaf node, it creates a new `Leaf` object and for each `Choice` node, `create` makes a new `Choice ` node.

If you look at the test, `tree` is not being modified, rather a new tree called `prunedTree` is being created.

**Comment by varunagrawal** [comment]
Just verified in the test by printing the trees after the assertion. `tree` is indeed unmodified.

**Comment by varunagrawal** [comment]
Also: https://github.com/borglab/gtsam/pull/1125

**Comment by varunagrawal** [comment]
Undid the changes so closing this PR.

**Pull request closed without merging**
