### PR TITLE
pybind11/stl.h

### PR DESCRIPTION
**Pull request by varunagrawal**

### CODE REVIEW

**Comment by dellaert** [comment]
If we merge in this then the fork becomes useless for hybrid, right?

**Comment by varunagrawal** [comment]
This is not related to hybrid. This was my attempt at giving full STL support to Pybind but we parked it because it is API breaking.

**Comment by dellaert** [comment]
Exactly. So we want a fork for you and @ProfFan that is clean except hybrid, right?

**Comment by varunagrawal** [comment]
I don't quite understand what do you mean by clean except for hybrid? This is just a separate branch on my own personal fork that I use for experimenting without clogging up the CI on the main repo.

**Comment by dellaert** [comment]
Maybe we should not be working in your personal fork. I'm interested in a fork in which we do the development for the hybrid inference framework without clogging up the CI, and nothing else.

**Comment by dellaert** [comment]
To be super clear, because communication seems to be breaking down again: the stuff with stl pybind does not seem related at all, and has the potential to create merge issues when we PR hybrid back into develop. That's why the fork needs to be clean except for hybrid. Does that make sense? Seems just common sense to me...

**Comment by varunagrawal** [comment]
> Maybe we should not be working in your personal fork. I'm interested in a fork in which we do the development for the hybrid inference framework without clogging up the CI, and nothing else.

I am open to suggestions. I don't know how else to fork GTSAM into something separate.



> To be super clear, because communication seems to be breaking down again: the stuff with stl pybind does not seem related at all, and has the potential to create merge issues when we PR hybrid back into develop. That's why the fork needs to be clean except for hybrid. Does that make sense? Seems just common sense to me...

Yes this PR won't be touched until after Hybrid is completed so no need to worry about merge issues. Even now there is nothing here that intersects with the hybrid code.

**Comment by dellaert** [comment]
OK, makes sense.

**Comment by varunagrawal** [comment]
Okay this PR is ready but it breaks the `CustomFactor` since pybind doesn't support passing arguments by reference. Here's a link to the issue: https://github.com/pybind/pybind11/issues/1200

**Pull request closed without merging**
