### PR TITLE
Fix Pruning

### PR DESCRIPTION
**Pull request by varunagrawal**
PR to fix the pruning. I added some assertions which fail so if we can get them to pass, we should be good.

### CODE REVIEW

**Comment by varunagrawal** [comment]
Quick question: does the DecisionTree actually handle `nullptrs`? From the current implementation, the state estimator is getting those nullptrs and throwing exceptions as a result.

Example output from the state estimator:
```
 1 1 0 1 1 0 1 1 0 1 1 Choice(FL1) 
 1 1 0 1 1 0 1 1 0 1 1 0 Leaf Jacobian factor on 3 keys: 
  Conditional density [x[0](0)3] 
  R = [      67.7027   0.00390897  -0.00753954   -0.0237068      7.35982     0.307122 ]
      [            0      67.9856   -0.0163348     -8.08179   -0.0401695     0.352128 ]
      [            0            0      67.0417     -0.34763    -0.562401    0.0101637 ]
      [            0            0            0      71.0515   -0.0163133 -0.000749471 ]
      [            0            0            0            0       70.009    -0.194946 ]
      [            0            0            0            0            0      72.4312 ]
  S[v[0](0)0] = [   0.00205433     0.226973    -0.119959 ]
                [    -0.208505    0.0019904     0.115424 ]
                [     0.123202    -0.118834   0.00392007 ]
                [     0.202636   0.00237579    0.0340421 ]
                [ -0.000135123     0.260336     0.031717 ]
                [   0.00337784    0.0110197     0.238347 ]
  S[x[0](0)0] = [      30.4444     0.131757     0.372429    0.0679382    -0.864654    -0.874949 ]
                [    -0.129282      29.8015    -0.181613      1.56267    0.0855477      2.15451 ]
                [    -0.377723     0.300975      32.4588     0.937058      -1.8746    0.0247286 ]
                [   -0.0374136      10.1264     -0.13871       13.226     0.149244     0.584521 ]
                [     -9.15332   -0.0516046      0.17247    -0.111527      15.5424     0.137806 ]
                [     0.164382    -0.380617 -0.000207735   -0.0818315     0.386119      11.1727 ]
  d = [ -0.195025  0.580265 -0.111603  -1.96092 -0.667385 0.0843062 ]
  No noise model


 1 1 0 1 1 0 1 1 0 1 1 1 Leaf nullptr

 1 1 0 1 1 0 1 1 1 Leaf nullptr

 1 1 0 1 1 1 Leaf nullptr

 1 1 1 Leaf nullptr

}
```

This throws the error: `ValueError: DecisionTree::operator(): value undefined for a label` which comes from `Choice::operator()` in `DecisionTree-inl.h`. If my intuition is correct, those nullptr leaves should be pruned away, so please correct me if I am wrong.

**Comment by varunagrawal** [comment]
I printed out the tree after this line which should be doing the pruning:
```cpp
GaussianMixture::Factors prunedConditionalsTree(lastDensity->discreteKeys(),
                                                    prunedConditionals);


prunedConditionalsTree.print("", DefaultKeyFormatter, [](const GaussianFactor::shared_ptr gf) { if(gf) gf->print("", DefaultKeyFormatter); return "";});
```

and I still get leaves where the nullptrs are, so pruning is not happening there.

**Comment by varunagrawal** [comment]
Output of tree printing (after I updated the valueFormatter to print `nullptr` is the gaussian factor is pointint to null):

```
 Choice(m3) 
 0 Choice(m2) 
 0 0 Leaf nullptr

 0 1 Choice(m1) 
 0 1 0 Leaf   Conditional density [x4] 
  R = [ 10.0494 ]
  d = [ -10.1479 ]
  No noise model

 0 1 1 Leaf   Conditional density [x4] 
  R = [ 10.0494 ]
  d = [ -10.1479 ]
  No noise model

 1 Choice(m2) 
 1 0 Choice(m1) 
 1 0 0 Leaf nullptr

 1 0 1 Leaf   Conditional density [x4] 
  R = [ 10.0494 ]
  d = [ -10.0504 ]
  No noise model

 1 1 Choice(m1) 
 1 1 0 Leaf   Conditional density [x4] 
  R = [ 10.0494 ]
  d = [ -10.0494 ]
  No noise model

 1 1 1 Leaf   Conditional density [x4] 
  R = [ 10.0494 ]
  d = [ -10.0494 ]
  No noise model
```

Please advise? @dellaert @ProfFan

**Comment by dellaert** [comment]
Please get together with Fan.

**Pull request closed without merging**
