### PR TITLE
HybridBayesNet private members

### PR DESCRIPTION
**Pull request by varunagrawal**
Moved member variables to private scope and added methods to allow for full functionality.

cc @dellaert

### CODE REVIEW

**Comment by dellaert** [comment]
Let @ProfFan review this level. Send me quadruped results :-)

**Comment by varunagrawal** [comment]
Sounds good! :D

**Review by ProfFan — APPROVED** [review]

**Comment by varunagrawal** [comment]
I'm going to wait on a review for #20 before merging this to reduce reviewer overhead.

**Comment by dellaert** [comment]
Why close it?

**Comment by varunagrawal** [comment]
I don't know, this was automatic after I merged #20. So strange.

**Pull request merged**
