### PR TITLE
Frank's Updates

### PR DESCRIPTION
**Pull request by varunagrawal**
A PR with @dellaert's latest changes to `discrete`.

### CODE REVIEW

**Comment by dellaert** [comment]
Why not just merge in develop??

**Comment by dellaert** [comment]
Again, why not merge in develop? Maybe that does not work on a fork?

**Comment by varunagrawal** [comment]
We can, but this PR now also has fixes for `feature/hybrid`.

**Comment by varunagrawal** [comment]
Merging this in.

**Pull request merged**
